### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by colomet** [humanmade/backupwordpress-pro-ftp#36]
Warning: require_once(/var/www/vhosts/myserver/mysite/wp-content/plugins/backupwordpress-pro-ftp/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/myserver/mysite/wp-content/plugins/backupwordpress-pro-ftp/backupwordpress-pro-ftp.php on line 33

Fatal error: require_once(): Failed opening required '/var/www/vhosts/myserver/mysite/wp-content/plugins/backupwordpress-pro-ftp/vendor/autoload.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/myserver/mysite/wp-content/plugins/backupwordpress-pro-ftp/backupwordpress-pro-ftp.php on line 33

**Comment by katmoody** [comment]
Hey there - I haven't seen this come up with the FTP plugin before - is this the newest version downloaded after purchase? I'd like to try and replicate it locally if possible.

**Comment by colomet** [comment]
is the one from github. I did not pay for FTP, I did pay for Dropbox, i was just testing while I find that.

**Comment by katmoody** [comment]
Hey there - if you could reach out on our dedicated support that would be great (either by emailing backupwordpress@hmn.md or clicking to "Enable Support" on the top of the BackUpWordPress admin page on your site). We don't generally handle support requests here on GitHub, but through those dedicated support channels. That way I can do further support with you as well as more troubleshooting! 

Thanks so much!

**Comment by pdewouters** [comment]
@colomet did you run `composer install`

**Comment by colomet** [comment]
no, thanks I will try.
